version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node@3.0.0
      # - image: alpine:3.7
    steps:
      - checkout
      - run: echo 'Hello World!'
          # name: The First Step
          # command: |
          #   echo 'Hello World!'
          #   echo 'This is the delivery pipeline'